### ISSUE TITLE
Using Point in Geospatial Queries

### ISSUE THREAD

**Issue by abuechler** [arangodb/spring-data-demo#19]
The example [1] shows a location as an array. As I read in the documentation [2], it can be either a geometry object or a coordinate array.

So what does this mean for the Java driver, is possible to use Point? E.g. like:

```
import org.springframework.data.geo.Point

@Document("locations")
public class Location {

  @Id
  private String id;
  private final String name;
  @GeoIndexed
  private final Point location;
```

I get errors when I do so and perform queries but maybe I'm missing something?

```
 Response: 404, Error: 1203 - AQL: collection or view not found: point (while parsing)
```

[1] https://github.com/arangodb/spring-data-demo#geo-data-modeling
[2] https://www.arangodb.com/docs/3.7/indexing-geo.html#geojson-mode

**Comment by rashtao** [comment]
Thanks for reporting @abuechler . 
I think this is a bug in spring-data-arangodb since `Point` is correctly serialized only when it is used as parameter in derived queries, eg. in https://github.com/arangodb/spring-data-demo/blob/e1d2f5898e0530e5b740667b529b5bcf4ca76948/src/main/java/com/arangodb/spring/demo/repository/LocationRepository.java#L40-L44
